GET http://localhost:4004/odata/v4/mainservice/SalesOrderHeaders
Content-Type: application/json

###

POST http://localhost:4004/odata/v4/mainservice/SalesOrderHeaders
Content-Type: application/json

{}

###

PUT  http://localhost:4004/odata/v4/mainservice/SalesOrderHeaders(id=fdf2fddc-2f70-46a9-806c-6f5d40a3b3bd)
Content-Type: application/json

{
    "modifiedby": "teste"
    }
    
